language: php

php:
  - 5.6
  - 7.0
  - hhvm

sudo: false

services:
  - mysql

before_script:
  - cp .env.travis .env
  - mysql -e 'create database app;'
  - composer self-update
  - composer install --prefer-source --no-interaction --dev
  - php artisan migrate
  - php artisan db:seed
  - php artisan key:generate

script: vendor/bin/phpunit